<?php
// This file is designed to be included in your main layout file.
// It contains the HTML and JavaScript for the Back to Top button.
// No PHP logic is needed directly within this file content itself
// unless the button's behavior needed to be dynamically generated by PHP.
?>

<button id="backToTopBtn"
	class="fixed bottom-6 right-6 bg-red-600 text-white p-3 rounded-full shadow-lg transition-opacity duration-300 ease-in-out z-50
		   opacity-0 pointer-events-none hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-red-500 focus:ring-opacity-50 print:hidden">
	<svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
		<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 10l7-7m0 0l7 7m-7-7v18" />
	</svg>
</button>

<script>
	// Get the button element
	const backToTopBtn = document.getElementById('backToTopBtn');
	// Define the scroll threshold (in pixels) when the button should appear
	const scrollThreshold = 300; // Adjust this value as needed

	// Function to toggle button visibility based on scroll position
	function toggleBackToTopButton() {
		// Check scroll position, using scrollY for modern browsers and scrollTop for others
		if (window.scrollY > scrollThreshold || document.documentElement.scrollTop > scrollThreshold) {
			// Add classes to make it visible and clickable
			backToTopBtn.classList.add('opacity-100', 'pointer-events-auto');
			backToTopBtn.classList.remove('opacity-0', 'pointer-events-none');
		} else {
			// Add classes to make it hidden and non-interactive
			backToTopBtn.classList.add('opacity-0', 'pointer-events-none');
			backToTopBtn.classList.remove('opacity-100', 'pointer-events-auto');
		}
	}

	// Function to smoothly scroll to the top of the page
	function scrollToTop() {
		// Use the browser's native smooth scrolling feature if available
		window.scrollTo({
			top: 0,
			behavior: 'smooth' // Smooth scrolling animation
		});
	}

	// Add a scroll event listener to the window to call the toggle function
	window.addEventListener('scroll', toggleBackToTopButton);

	// Add a click event listener to the button to call the scroll function
	backToTopBtn.addEventListener('click', scrollToTop);

	// Call the toggle function once when the page loads in case the page is already scrolled
	toggleBackToTopButton();
</script>